const colors = {
  light: {
    text: '#1a2240',
    tint: '#3658ca',
    background: '#f6f8fc',
    foreground: '#1a2240',
    card: '#ffffff',
    cardForeground: '#1a2240',
    primary: '#3658ca',
    primaryForeground: '#ffffff',
    secondary: '#edf0f8',
    secondaryForeground: '#1a2240',
    muted: '#edf0f8',
    mutedForeground: '#5a6a8a',
    accent: '#1bafad',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#dce3f2',
    input: '#dce3f2',
    success: '#22c55e',
    successForeground: '#ffffff',
    warning: '#f59e0b',
    warningForeground: '#ffffff',
  },
  dark: {
    text: '#f6f8fc',
    tint: '#5b7ce8',
    background: '#070b12',
    foreground: '#f6f8fc',
    card: '#0b1120',
    cardForeground: '#f6f8fc',
    primary: '#3658ca',
    primaryForeground: '#ffffff',
    secondary: '#1a2140',
    secondaryForeground: '#f6f8fc',
    muted: '#1a2140',
    mutedForeground: '#8f9eb8',
    accent: '#1bafad',
    accentForeground: '#ffffff',
    destructive: '#c0392b',
    destructiveForeground: '#ffffff',
    border: '#1a2140',
    input: '#1a2140',
    success: '#16a34a',
    successForeground: '#ffffff',
    warning: '#d97706',
    warningForeground: '#ffffff',
  },
  radius: 10,
};

export default colors;
