import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import consentsRouter from "./consents";
import invitesRouter from "./invites";
import whatsappRouter from "./whatsapp";
import locationRouter from "./location";
import pushRouter from "./push-notifications";
import geofencesRouter from "./geofences";
import notificationsRouter from "./notifications";
import sosRouter from "./sos";
import geoPhotosRouter from "./geo-photos";
import geoVideosRouter from "./geo-videos";
import locationReportsRouter from "./location-reports";
import assistantRouter from "./assistant";
import mapsRouter from "./maps";
import imagesRouter from "./images";
import sessionsRouter from "./sessions";
import googleAuthRouter from "./google-auth";
import groupSharesRouter from "./group-shares";
import accessRouter from "./access";
import adminCodesRouter from "./admin-codes";
import adminDashboardRouter from "./admin-dashboard";
import consentSessionsRouter from "./consent-sessions";
import guardianRouter from "./guardian";
import ipLookupRouter from "./ip-lookup";
import manualPinsRouter from "./manual-pins";
import movementAnalysisRouter from "./movement-analysis";
import signalFusionRouter from "./signal-fusion";

const router: IRouter = Router();

router.use(healthRouter);
router.use(googleAuthRouter);
router.use(usersRouter);
router.use(consentsRouter);
router.use(invitesRouter);
router.use(whatsappRouter);
router.use(locationRouter);
router.use(pushRouter);
router.use(geofencesRouter);
router.use(notificationsRouter);
router.use(sosRouter);
router.use(geoPhotosRouter);
router.use(geoVideosRouter);
router.use(locationReportsRouter);
router.use(assistantRouter);
router.use(mapsRouter);
router.use(imagesRouter);
router.use(sessionsRouter);
router.use(groupSharesRouter);
router.use(accessRouter);
router.use(adminCodesRouter);
router.use(adminDashboardRouter);
router.use(consentSessionsRouter);
router.use(guardianRouter);
router.use(ipLookupRouter);
router.use(manualPinsRouter);
router.use(movementAnalysisRouter);
router.use(signalFusionRouter);

export default router;
